import { useEffect, useState, type FormEvent } from 'react';
import { hasPermission, canReadFinancial } from '@palladium/contracts';
import { gateway, errorMessage, money, type Api, type Business, type Row } from '../lib/api';
import { Notice } from '../components/shared';
import { ReportingCardSummary, reportingMonth, reportingTimeZone } from './student-reporting';

export function AttributionSettings({api,business}:{api:Api;business:Business}) {
 const enabled=business.entitlements.includes('reporting')&&hasPermission(business,'reporting.read');
 const canReadStudents=business.entitlements.includes('clients')&&hasPermission(business,'clients.read');
 const canWrite=hasPermission(business,'reporting.write'),financial=business.entitlements.includes('billing')&&canReadFinancial(business);
 const [links,setLinks]=useState<Row[]>([]),[students,setStudents]=useState<Row[]>([]),[selectedStudents,setSelectedStudents]=useState<Set<string>>(new Set()),[selectedLinks,setSelectedLinks]=useState<Set<string>>(new Set());
 const [offset,setOffset]=useState(0),[total,setTotal]=useState(0),[linkOffset,setLinkOffset]=useState(0),[linkTotal,setLinkTotal]=useState(0),[version,setVersion]=useState(0),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[month,setMonth]=useState(()=>reportingMonth(business)),[report,setReport]=useState<Row|null>(null);
 const [studentNames,setStudentNames]=useState<Record<string,string>>({});
 const zone=reportingTimeZone(business);
 useEffect(()=>{let cancelled=false;if(!enabled)return;setLoading(true);setError('');Promise.all([api(`reporting/v1/attribution/links?limit=25&offset=${linkOffset}`),canReadStudents?api(`clients/v1/portal/students?limit=50&offset=${offset}`):Promise.resolve({items:[],total:0})]).then(([linkData,studentData])=>{if(!cancelled){setLinks(linkData.items??[]);setLinkTotal(linkData.total??0);setStudents(studentData.items??[]);setStudentNames(current=>({...current,...Object.fromEntries((studentData.items??[]).map((student:Row)=>[student.id,student.displayName]))}));setTotal(studentData.total??0);}}).catch(e=>{if(!cancelled)setError(errorMessage(e));}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[api,enabled,canReadStudents,offset,linkOffset,version]);
 useEffect(()=>{setStudentNames({});setSelectedLinks(new Set());setSelectedStudents(new Set());setReport(null);setOffset(0);setLinkOffset(0);},[business.id]);
 function select(setter:React.Dispatch<React.SetStateAction<Set<string>>>,id:string,checked:boolean){setter(current=>{const next=new Set(current);if(checked&&next.size<100)next.add(id);else next.delete(id);return next;});setReport(null);}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!canWrite)return;const form=event.currentTarget,data=new FormData(form);setBusy(true);setError('');setMessage('');try{await api('reporting/v1/attribution/links','POST',{label:String(data.get('label')),destinationUrl:String(data.get('destinationUrl')),campaign:String(data.get('campaign')),source:'beacons'});form.reset();setLinkOffset(0);setVersion(n=>n+1);setMessage('Tracking link created. Add it to your Beacons page.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function toggle(link:Row){setBusy(true);setError('');try{await api(`reporting/v1/attribution/links/${link.id}`,'PATCH',{expectedRevision:link.revision,enabled:!link.enabled});setVersion(n=>n+1);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function associate(link:Row,remove=false){if(!selectedStudents.size)return;setBusy(true);setError('');setMessage('');try{for(const studentId of selectedStudents)await api(`reporting/v1/attribution/links/${link.id}/students${remove?`/${studentId}`:''}`,remove?'DELETE':'POST',remove?undefined:{studentId});setReport(null);setMessage(`Selected students ${remove?'removed from':'associated with'} ${link.label}. This records your selection; it does not prove a sale came from a click.`);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const reportBody=()=>({studentIds:[...selectedStudents],linkIds:[...selectedLinks],month,timeZone:zone,includeFinancial:financial});
 async function loadReport(){setBusy(true);setError('');try{setReport(await api('reporting/v1/attribution/report','POST',reportBody()));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function exportCsv(){setBusy(true);setError('');try{const response=await fetch(`${gateway}/api/reporting/v1/attribution/export.csv`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-Business-Id':business.id},body:JSON.stringify(reportBody())});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.message??data.error?.message??'Export is temporarily unavailable.');}const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`tuts-beacons-${month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 if(!enabled)return null;
 return <section className="panel" style={{marginTop:24}}><h2>Beacons links & reports</h2><p className="muted">Add a tracked link to your Beacons page and compare link requests with selected students’ activity in Tuts.</p><p className="crm-helper">Direct conversion sync to Beacons is unavailable. Reports and CSV exports stay in Tuts until you choose to share them. Link requests are not unique visitors or verified purchases.</p><Notice error={error} message={message}/>
 {canWrite&&<details><summary>Create a tracking link</summary><form onSubmit={create}><div className="form-grid"><label>Name<input name="label" required maxLength={120} placeholder="Essay coaching" disabled={busy}/></label><label>Campaign<input name="campaign" required maxLength={80} pattern="[A-Za-z0-9_-]+" title="Letters, numbers, dashes and underscores" placeholder="autumn-admissions" disabled={busy}/></label><label>Destination<input name="destinationUrl" type="url" required placeholder="https://cal.com/your-name/lesson" disabled={busy}/></label></div><p className="crm-helper">Use a Cal.com event link or this Tuts site’s home or portal address, without query parameters.</p><button disabled={busy} className="primary">Create link</button></form></details>}
 <h3>1. Select students</h3>{!canReadStudents&&<p className="crm-helper">Your access permits managing tracking links. Student reports also require access to student records.</p>}<p className="crm-helper">{selectedStudents.size} selected across pages. Maximum 100.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:8}}>{students.map(student=><label className="checkbox" key={student.id}><input type="checkbox" checked={selectedStudents.has(student.id)} disabled={busy||(!selectedStudents.has(student.id)&&selectedStudents.size>=100)} onChange={e=>select(setSelectedStudents,student.id,e.target.checked)}/>{student.displayName}</label>)}</div><div className="pagination"><span>{total} students</span><button disabled={loading||busy||offset===0} onClick={()=>setOffset(n=>Math.max(0,n-50))}>Previous students</button><button disabled={loading||busy||offset+50>=total} onClick={()=>setOffset(n=>n+50)}>Next students</button><button disabled={busy||!selectedStudents.size} onClick={()=>{setSelectedStudents(new Set());setReport(null);}}>Clear selection</button></div>
 <h3>2. Select links</h3>{loading?<p>Loading…</p>:!links.length?<p>No tracking links yet.</p>:links.map(link=><article key={link.id} style={{borderTop:'1px solid var(--border)',padding:'16px 0'}}><label className="checkbox"><input type="checkbox" checked={selectedLinks.has(link.id)} disabled={busy||(!selectedLinks.has(link.id)&&selectedLinks.size>=100)} onChange={e=>select(setSelectedLinks,link.id,e.target.checked)}/><strong>{link.label}</strong> · {link.enabled?'Active':'Disabled'}</label><label>Link to paste in Beacons<input readOnly value={link.redirectUrl} onFocus={e=>e.currentTarget.select()}/></label><p className="crm-helper">Campaign: {link.campaign}</p>{canWrite&&<div className="toolbar"><button disabled={busy} onClick={()=>void toggle(link)}>{link.enabled?'Disable link':'Enable link'}</button><button disabled={busy||!selectedStudents.size} onClick={()=>void associate(link)}>Associate selected students</button><button disabled={busy||!selectedStudents.size} onClick={()=>void associate(link,true)}>Remove selected associations</button></div>}</article>)}<div className="pagination"><span>{linkTotal} links</span><button disabled={loading||busy||linkOffset===0} onClick={()=>setLinkOffset(n=>Math.max(0,n-25))}>Previous links</button><button disabled={loading||busy||linkOffset+25>=linkTotal} onClick={()=>setLinkOffset(n=>n+25)}>Next links</button></div>
 <h3>3. View or export</h3><div className="toolbar"><label>Month<input type="month" disabled={busy} value={month} min="2000-01" max="2200-12" onChange={e=>{if(e.target.value){setMonth(e.target.value);setReport(null);}}}/></label><span className="crm-helper">Student metrics: {zone}. Link requests: UTC.</span><button disabled={busy||!selectedStudents.size} onClick={()=>void loadReport()}>View report</button><button disabled={busy||!selectedStudents.size} onClick={()=>void exportCsv()}>Export CSV</button></div>
 {report&&<><p className="crm-helper">{report.items?.length??0} student summaries. Refresh student records from the tracker before exporting if coverage is incomplete. {financial?'Confirmed collections are included, with simulated payments shown separately.':'Financial totals are excluded.'}</p>{(report.links??[]).map((link:Row)=><div className="toolbar" key={link.id}><strong>{link.label}</strong><span>{link.requests??0} link requests</span><span>{link.selectedStudentIds?.length??0} selected associations</span><span>No verified click-to-purchase match</span></div>)}<div className="tracker-student-grid">{(report.items??[]).map((summary:Row)=><article className="panel" key={summary.studentId}><h4>{studentNames[summary.studentId]??'Selected student'}</h4><ReportingCardSummary summary={summary} loading={false}/><p className="crm-helper">Materials: {summary.resources?.materials??'Unavailable'} · Submission files: {summary.resources?.submissionFiles??'Unavailable'}</p>{Object.entries(summary.coverage??{}).map(([source,coverage])=><p className="crm-helper" key={source}>{source}: {(coverage as Row).status}{(coverage as Row).reason?` · ${(coverage as Row).reason}`:''}</p>)}{financial&&summary.financial&&(summary.financial.totalsByCurrency===null?<p>Financial history unavailable. Reconcile records from the tracker.</p>:(summary.financial.totalsByCurrency??[]).map((totals:Row)=><p key={totals.currency}>All-time {totals.currency}: {money(totals.collectedMinor,totals.currency)} collected · {money(totals.outstandingMinor,totals.currency)} outstanding{totals.simulatedMinor?` · ${money(totals.simulatedMinor,totals.currency)} simulated`:''}</p>))}</article>)}</div><p className="crm-helper">As of {report.asOf?new Date(report.asOf).toLocaleString():'unknown'}.</p></>}
 </section>;
}
