import { useEffect, useState } from "react";
import { errorMessage, type Api, type Row } from "../lib/api";
import { Empty, Modal, Notice } from "../components/shared";
import "./student-contacts.css";

type Pair = { source: Row; target: Row; reasons: string[] };
type AddressKind = "email" | "phone";
type Preview = { source: Row; target: Row; conflicts: { field: string; source: unknown; target: unknown }[]; contactAddresses: Record<AddressKind, { value: string; label: string }[]>; primaryAddresses: Partial<Record<AddressKind, string>>; affectedLinks: Record<string, number>; blockedReasons: string[]; sourceRevision: number; targetRevision: number };
function valueText(value: unknown): string { if (value == null || value === "") return "No value"; if (typeof value === "boolean") return value ? "Yes" : "No"; if (Array.isArray(value)) return value.map(valueText).join(", "); if (typeof value === "object") return JSON.stringify(value); return String(value); }
const fieldLabels: Record<string, string> = { displayName: "Display name", firstName: "First name", lastName: "Last name", email: "Email", phone: "Phone", status: "Stage", source: "Source", notes: "Notes", photo: "Student photo", emailOptIn: "Email updates permitted", whatsappOptIn: "WhatsApp updates permitted" };
function Person({ student }: { student: Row }) { return <div className="duplicate-person"><strong>{student.displayName}</strong><small>{student.email || "No email"}</small>{student.phone && <small>{student.phone}</small>}<small>{student.kind === "payer" ? "Parent / payer" : "Student"} · {student.status ?? "active"}</small><small>Record …{String(student.id).slice(-8)}</small></div>; }

export function DuplicateReview({ api, canWrite, canMerge, fieldLabels: customLabels = {}, onClose, onChanged }: { api: Api; canWrite: boolean; canMerge: boolean; fieldLabels?: Record<string, string>; onClose: () => void; onChanged: () => void }) {
  const [pairs, setPairs] = useState<Pair[]>([]), [total, setTotal] = useState(0), [offset, setOffset] = useState(0), [revision, setRevision] = useState(0);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [preview, setPreview] = useState<Preview | null>(null), [choices, setChoices] = useState<Record<string, "source" | "target">>({}), [confirmed, setConfirmed] = useState(false);
  const [primaryAddresses, setPrimaryAddresses] = useState<Partial<Record<AddressKind, string>>>({});
  useEffect(() => { let cancelled = false; setLoading(true); setError(""); api(`clients/v1/duplicates?limit=20&offset=${offset}`).then((data) => { if (!cancelled) { setPairs(data.items ?? []); setTotal(data.total ?? 0); } }).catch((e) => { if (!cancelled) setError(errorMessage(e)); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [api, offset, revision]);
  async function inspect(sourceId: string, targetId: string) { setBusy(true); setError(""); setMessage(""); setPreview(null); setChoices({}); setPrimaryAddresses({}); setConfirmed(false); try { const data = await api("clients/v1/merges/preview", "POST", { sourceId, targetId }); setPreview(data.item); setPrimaryAddresses(data.item.primaryAddresses); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function dismiss(pair: Pair) { if (!canWrite) return; setBusy(true); setError(""); try { await api("clients/v1/duplicates/dismiss", "POST", { sourceId: pair.source.id, targetId: pair.target.id }); setMessage("Records kept separate. This pair will be hidden from future duplicate reviews."); setRevision((n) => n + 1); onChanged(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function merge() { if (!preview || !canMerge || !confirmed || preview.blockedReasons.length || preview.conflicts.some((conflict) => !choices[conflict.field])) return; setBusy(true); setError(""); try { await api("clients/v1/merges", "POST", { sourceId: preview.source.id, targetId: preview.target.id, sourceRevision: preview.sourceRevision, targetRevision: preview.targetRevision, fieldChoices: choices, primaryAddresses }); setPreview(null); setConfirmed(false); setMessage("Student records merged. All student email addresses and phone numbers were kept. Linked services will update their references as the merge is processed."); setRevision((n) => n + 1); onChanged(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title={preview ? "Review student merge" : "Review possible duplicates"} onClose={() => { if (!busy) onClose(); }}>
    <Notice error={error} message={message} />
    {preview ? <>
      <p className="crm-helper">Check that both records describe the same person. Their email addresses and phone numbers will be combined; choose a primary address and review any other differences below.</p>
      <div className="duplicate-pair"><div><h3>Record to merge</h3><Person student={preview.source} /></div><div><h3>Record to keep</h3><Person student={preview.target} /></div></div>
      <div className="student-contact-actions"><button disabled={busy} onClick={() => void inspect(preview.target.id, preview.source.id)}>Keep the other record instead</button><button disabled={busy} onClick={() => void inspect(preview.source.id, preview.target.id)}>Refresh merge preview</button></div>
      <div className="duplicate-link-summary">{Object.entries(preview.affectedLinks).map(([name, count]) => <span className="tag" key={name}>{count} {({ contacts: "related contacts", payers: "payer relationships", sourceIdentities: "source identities", groups: "group memberships" } as Record<string, string>)[name] ?? name}</span>)}</div>
      <p className="student-contact-warning">Issued invoices keep their original recipient and financial snapshots. Merging preserves the old record as an alias, combines contact and source links, and asks linked services to update their student references. Portal access is never transferred by a merge.</p>
      {preview.blockedReasons.length > 0 && <div role="alert" className="alert error"><strong>This merge is blocked.</strong><ul>{preview.blockedReasons.map((reason, index) => <li key={index}>{reason}</li>)}</ul></div>}
      <section className="duplicate-addresses" aria-label="Contact details to keep">
        <h3>Keep all contact details</h3>
        <p className="crm-helper">All addresses below will be saved on the student’s contact. The primary address is used by default when contacting them. Family and payer contacts stay separate.</p>
        {(["email", "phone"] as const).map((kind) => {
          const addresses = preview.contactAddresses[kind];
          if (!addresses.length) return null;
          return <fieldset key={kind} disabled={busy}>
            <legend>{kind === "email" ? "Email addresses" : "Phone numbers"} · {addresses.length} to keep</legend>
            <ul className="duplicate-retained-addresses">{addresses.map((address) => <li key={address.value}><span>{address.value}</span>{address.label !== "personal" && <small>{address.label}</small>}<span className="tag">{primaryAddresses[kind] === address.value ? "Primary" : "Additional"}</span></li>)}</ul>
            {addresses.length > 1 && <label>Primary {kind === "email" ? "email" : "phone"}<select value={primaryAddresses[kind] ?? ""} onChange={(event) => { setPrimaryAddresses({ ...primaryAddresses, [kind]: event.target.value }); setConfirmed(false); }}>{addresses.map((address) => <option key={address.value} value={address.value}>{address.value}</option>)}</select></label>}
          </fieldset>;
        })}
        {!preview.contactAddresses.email.length && !preview.contactAddresses.phone.length && <p className="crm-helper">Neither student record has an email address or phone number.</p>}
      </section>
      <div className="duplicate-conflicts">{preview.conflicts.map((conflict) => <div className="duplicate-conflict" key={conflict.field}><fieldset disabled={busy}><legend>{customLabels[conflict.field] ?? fieldLabels[conflict.field] ?? conflict.field}</legend>{(["source", "target"] as const).map((side) => <label className="duplicate-value" key={side}><input type="radio" name={`merge-${conflict.field}`} checked={choices[conflict.field] === side} onChange={() => { setChoices({ ...choices, [conflict.field]: side }); setConfirmed(false); }} /><span><strong>{side === "target" ? "Keep" : "Use from merged record"}:</strong> {conflict.field === "photo" && typeof conflict[side] === "string" && /^data:image\/(png|jpeg|webp);base64,/.test(conflict[side]) ? <img src={conflict[side]} alt={`${side === "target" ? "Surviving" : "Merged"} student photo`} style={{ display: "block", width: 72, height: 72, borderRadius: 8, objectFit: "cover", marginTop: 8 }} /> : valueText(conflict[side])}</span></label>)}</fieldset></div>)}</div>
      {!preview.conflicts.length && <p className="crm-helper">No conflicting fields. Tags will be combined and missing values retained.</p>}
      <label className="duplicate-confirm"><input type="checkbox" checked={confirmed} disabled={busy || !canMerge || preview.blockedReasons.length > 0} onChange={(e) => setConfirmed(e.target.checked)} /><span>I checked these are the same person and approve merging <strong>{preview.source.displayName}</strong> into <strong>{preview.target.displayName}</strong>. Issued invoices will be preserved.</span></label>
      <div className="form-actions"><button disabled={busy} onClick={() => { setPreview(null); setError(""); }}>Back to duplicates</button><button className="primary" disabled={busy || !canMerge || !confirmed || preview.blockedReasons.length > 0 || preview.conflicts.some((c) => !choices[c.field])} onClick={() => void merge()}>{busy ? "Merging…" : "Confirm merge"}</button></div>
    </> : <>
      <p className="crm-helper">Matching names or contact details suggest a review. Shared family emails are valid; check each pair before making a decision.</p>
      {loading ? <Empty>Loading duplicate candidates…</Empty> : !pairs.length ? <Empty>No possible duplicates on this page.</Empty> : <div className="duplicate-list">{pairs.map((pair) => <article className="duplicate-card" key={`${pair.source.id}-${pair.target.id}`}><div className="duplicate-pair"><Person student={pair.source} /><Person student={pair.target} /></div><ul className="duplicate-reasons">{pair.reasons.map((reason, index) => <li key={index}>{reason}</li>)}</ul><div className="student-contact-actions">{canWrite && <button disabled={busy} onClick={() => void dismiss(pair)}>Keep separate</button>}{canMerge && <button className="primary" disabled={busy} onClick={() => void inspect(pair.source.id, pair.target.id)}>Preview merge</button>}</div></article>)}</div>}
      <div className="pagination"><span>{total} possible duplicate pairs</span><button disabled={loading || busy || offset === 0} onClick={() => setOffset((n) => Math.max(0, n - 20))}>Previous</button><button disabled={loading || busy || offset + 20 >= total} onClick={() => setOffset((n) => n + 20)}>Next</button></div>
    </>}
  </Modal>;
}
