import { useEffect, useState } from "react";
import { canReadFinancial, hasPermission } from "@palladium/contracts";
import { date, errorMessage, money, type Api, type Business, type Row } from "../lib/api";
import { Empty, Notice } from "../components/shared";
import "./student-reporting.css";

export function reportingTimeZone(business: Business) { const zone = business.settings?.timezone ?? "UTC"; try { new Intl.DateTimeFormat("en", { timeZone: zone }); return zone; } catch { return "UTC"; } }
export function reportingMonth(business: Business) { const parts = new Intl.DateTimeFormat("en", { year: "numeric", month: "2-digit", timeZone: reportingTimeZone(business) }).formatToParts(new Date()); return `${parts.find((part) => part.type === "year")?.value}-${parts.find((part) => part.type === "month")?.value}`; }
export function activeTime(seconds: unknown) { if (typeof seconds !== "number") return "Unavailable"; const minutes = Math.floor(seconds / 60); return seconds > 0 && minutes === 0 ? "Less than 1m" : minutes >= 60 ? `${Math.floor(minutes / 60)}h ${minutes % 60}m` : `${minutes}m`; }
function metric(value: unknown, coverage?: Row) { if (typeof value !== "number") return "Unavailable"; return `${value}${coverage?.status === "partial" ? " recorded" : ""}`; }
function coverageLabel(value: Row) { return ({ missing: "History missing", partial: "Partial history", complete: "Reconciled", unavailable: "Source unavailable" } as Record<string, string>)[value.status] ?? value.status; }

export function ReportingCardSummary({ summary, loading, error }: { summary?: Row; loading: boolean; error?: string }) {
  if (loading) return <p className="tracker-summary-note">Loading progress summary…</p>;
  if (error) return <p className="tracker-summary-note">Progress summary unavailable. {error}</p>;
  if (!summary) return <p className="tracker-summary-note">Progress summary is not available for this student.</p>;
  const hasHistory = typeof summary.bookings?.completed === "number" || typeof summary.homework?.submitted === "number";
  return <div className="tracker-summary-note">{hasHistory ? <dl className="tracker-card-metrics">
    <div><dt>Classes completed</dt><dd>{metric(summary.bookings?.completed, summary.coverage?.scheduling)}</dd></div>
    <div><dt>Homework to review</dt><dd>{metric(summary.homework?.submitted, summary.coverage?.learning)}</dd></div>
    <div><dt>Homework in progress</dt><dd>{typeof summary.homework?.assigned === "number" && typeof summary.homework?.needsRevision === "number" ? metric(summary.homework.assigned + summary.homework.needsRevision, summary.coverage?.learning) : "Unavailable"}</dd></div>
  </dl> : <p>Progress will appear as sessions and homework are recorded.</p>}
  <p>Last active: {summary.activity?.lastSeenAt ? date(summary.activity.lastSeenAt) : "Not recorded yet"}</p>
  {summary.partial && hasHistory && <small>Some history is incomplete. Open the student for details.</small>}</div>;
}

export function StudentReporting({ api, business, studentId, month, onMonthChange, activityOnly = false }: { api: Api; business: Business; studentId: string; month: string; onMonthChange: (month: string) => void; activityOnly?: boolean }) {
  const allowed = business.entitlements.includes("reporting") && hasPermission(business, "reporting.read"), canReconcile = hasPermission(business, "reporting.write") && ["owner", "admin", "tutor"].includes(business.role), includeFinancial = business.entitlements.includes("billing") && canReadFinancial(business);
  const zone = reportingTimeZone(business), [summary, setSummary] = useState<Row | null>(null), [days, setDays] = useState<Row[]>([]), [total, setTotal] = useState(0), [offset, setOffset] = useState(0), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [revision, setRevision] = useState(0);
  useEffect(() => { setOffset(0); }, [month, studentId]);
  useEffect(() => {
    let cancelled = false; setSummary(null); setDays([]); setError(""); if (!allowed) { setLoading(false); return; } setLoading(true);
    const query = new URLSearchParams({ month, timeZone: zone, includeFinancial: String(includeFinancial) }), history = new URLSearchParams({ month, timeZone: zone, limit: "20", offset: String(offset) });
    Promise.all([api(`reporting/v1/students/${studentId}/summary?${query}`), ...(activityOnly ? [api(`reporting/v1/students/${studentId}/activity?${history}`)] : [])]).then((data) => { if (!cancelled) { setSummary(data[0].item); if (data[1]) { setDays(data[1].items ?? []); setTotal(data[1].total ?? 0); } } }).catch((e) => { if (!cancelled) setError(errorMessage(e)); }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [api, allowed, studentId, month, zone, includeFinancial, activityOnly, offset, revision]);
  async function reconcile() { if (!allowed || !canReconcile) return; setBusy(true); setError(""); try { const data = await api(`reporting/v1/students/${studentId}/reconcile`, "POST", { month, timeZone: zone, includeFinancial }); setSummary(data.item); if (activityOnly) setRevision((n) => n + 1); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  if (!allowed) return <Empty>Progress and activity summaries are not available with your current access.</Empty>;
  return <section className="student-reporting" aria-label={activityOnly ? "Student activity history" : "Student progress summary"}>
    <Notice error={error} /><div className="tracker-actions"><label>Month<input type="month" value={month} min="2000-01" max="2200-12" disabled={busy} onChange={(e) => { if (/^\d{4}-\d{2}$/.test(e.target.value)) onMonthChange(e.target.value); }} /></label><span className="crm-helper">{zone}</span><button disabled={loading || busy} onClick={() => setRevision((n) => n + 1)}>Refresh summary</button>{canReconcile && <button disabled={loading || busy} onClick={() => void reconcile()}>{busy ? "Updating progress…" : "Update from sessions & homework"}</button>}</div>
    {loading ? <Empty>Loading {activityOnly ? "activity" : "progress"}…</Empty> : summary && <>
      {summary.asOf && <p className="crm-helper">Summary updated {date(summary.asOf)}{summary.partial ? " · Partial history" : ""}. Month boundaries use {zone}.</p>}
      <div className="tracker-summary-grid">{!activityOnly && <><div className="tracker-detail-item"><h3>Sessions</h3><dl className="tracker-properties">{([['booked','Booked'],['completed','Completed'],['cancelled','Cancelled'],['noShow','No-shows']] as const).map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{metric(summary.bookings?.[key], summary.coverage?.scheduling)}</dd></div>)}</dl></div><div className="tracker-detail-item"><h3>Homework</h3><dl className="tracker-properties">{([['assigned','Assigned'],['submitted','Awaiting review'],['completed','Completed'],['needsRevision','Needs another attempt']] as const).map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{metric(summary.homework?.[key], summary.coverage?.learning)}</dd></div>)}</dl></div></>}<div className="tracker-detail-item"><h3>Activity in Tuts</h3><dl className="tracker-properties"><div><dt>Estimated active time</dt><dd>{activeTime(summary.activity?.activeSeconds)}</dd></div><div><dt>Last activity</dt><dd>{summary.activity?.lastSeenAt ? date(summary.activity.lastSeenAt) : "Not recorded"}</dd></div></dl><p className="crm-helper">Counts visible Tuts interaction, with capped gaps and overlapping tabs deduplicated. Time in external Google Docs is unavailable.</p></div></div>
      {!activityOnly && includeFinancial && <div className="tracker-detail-item"><h3>Financial summary · all time</h3>{summary.financial?.totalsByCurrency == null ? <p className="crm-helper">Financial history is unavailable or incomplete.</p> : !summary.financial.totalsByCurrency.length ? <p className="crm-helper">No issued financial records have been reconciled.</p> : summary.financial.totalsByCurrency.map((total: Row) => <dl className="tracker-properties" key={total.currency}><div><dt>Billed · {total.currency}</dt><dd>{money(total.billedMinor, total.currency)}</dd></div><div><dt>Collected</dt><dd>{money(total.collectedMinor, total.currency)}</dd></div><div><dt>Outstanding</dt><dd>{money(total.outstandingMinor, total.currency)}</dd></div>{total.simulatedMinor > 0 && <div><dt>Sandbox simulations</dt><dd>{money(total.simulatedMinor, total.currency)}</dd></div>}</dl>)}</div>}
      {!activityOnly && <details className="tracker-coverage"><summary>About these numbers</summary>{Object.entries(summary.coverage ?? {}).filter(([domain]) => domain !== "billing" || includeFinancial).map(([domain, value]) => <div className="tracker-detail-item" key={domain}><strong>{({ scheduling: "Sessions", learning: "Learning", billing: "Billing" } as Record<string, string>)[domain] ?? domain}</strong><p className="crm-helper">{coverageLabel(value as Row)}{(value as Row).asOf ? ` · Updated ${date((value as Row).asOf)}` : ""}{(value as Row).reason ? ` · ${(value as Row).reason}` : ""}</p></div>)}</details>}
      {activityOnly && <><h3>Daily activity · estimated</h3>{!days.length ? <Empty>No activity recorded for this month.</Empty> : <div className="tracker-detail-list">{days.map((day) => <div className="tracker-detail-item" key={day.date}><strong>{day.date}</strong><p>{activeTime(day.activeSeconds)} active in Tuts{day.lastSeenAt ? ` · Last seen ${date(day.lastSeenAt)}` : ""}</p></div>)}</div>}{total > 20 && <div className="pagination"><span>{total ? `${offset + 1}–${Math.min(offset + days.length, total)} of ${total} days` : ""}</span><button disabled={loading || offset === 0} onClick={() => setOffset((n) => Math.max(0, n - 20))}>Previous</button><button disabled={loading || offset + 20 >= total} onClick={() => setOffset((n) => n + 20)}>Next</button></div>}</>}
    </>}
  </section>;
}
