import { useEffect, useState, type FormEvent } from "react";
import { hasPermission } from "@palladium/contracts";
import { date, errorMessage, type Api, type Business, type Row } from "../lib/api";
import { Empty, Modal, Notice } from "../components/shared";
import { StudentBoardCard } from "./student-board-card";
import { StudentBoardTemplates } from "./student-board-template";
import { StudentBoardTemplateReview } from "./student-board-template-review";
import { positionBetween } from "../lib/kanban-order";
import { StudentBoardKanban } from "./student-board-kanban";
import "./student-boards.css";

export function StudentBoards({ api, business, studentId, student }: { api: Api; business: Business; studentId: string; student?: Row }) {
  const allowed = business.entitlements.includes("planning") && hasPermission(business, "planning.read"), canWrite = allowed && hasPermission(business, "planning.write"), canCreate = canWrite && hasPermission(business, "clients.read");
  const [boards, setBoards] = useState<Row[]>([]), [total, setTotal] = useState(0), [offset, setOffset] = useState(0), [boardId, setBoardId] = useState<string | null>(null), [detail, setDetail] = useState<Row | null>(null), [revision, setRevision] = useState(0);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState(""), [boardEditor, setBoardEditor] = useState<Row | null>(null), [columnEditor, setColumnEditor] = useState<Row | null>(null), [cardEditor, setCardEditor] = useState<Row | null>(null), [templates, setTemplates] = useState(false), [templateReview, setTemplateReview] = useState(false);
  useEffect(() => { setBoardId(null); setDetail(null); setOffset(0); setBoardEditor(null); setColumnEditor(null); setCardEditor(null); setTemplates(false); setTemplateReview(false); }, [studentId, business.id]);
  useEffect(() => { let cancelled = false; setError(""); setLoading(true); setDetail(null); if (!allowed) { setLoading(false); return; } const load = boardId ? api(`planning/v1/boards/${boardId}`) : api(`planning/v1/boards?${new URLSearchParams({ studentId, limit: "20", offset: String(offset) })}`); load.then((data) => { if (!cancelled) { if (boardId) setDetail(data); else { setBoards(data.items ?? []); setTotal(data.total ?? 0); } } }).catch((e) => { if (!cancelled) setError(errorMessage(e)); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [api, allowed, boardId, studentId, offset, revision]);
  async function refreshBoard(failureMessage = "The change was saved, but the board could not be refreshed. Refresh before making another change.") { if (!boardId) { setRevision((n) => n + 1); return; } try { const data = await api(`planning/v1/boards/${boardId}`); setDetail(data); } catch (e) { setError(`${failureMessage} ${errorMessage(e)}`); setDetail(null); } }
  const board = detail?.item?.studentId === studentId ? detail.item : null, canManage = canWrite && detail?.canManageStructure === true, columns: Row[] = [...(detail?.columns ?? [])].sort((a, b) => a.position - b.position || a.id.localeCompare(b.id)), cards: Row[] = detail?.cards ?? [];
  async function move(card: Row, columnId: string, position: number) {
    if (!canWrite || !board || busy) return;
    const saved = detail; setBusy(true); setError(""); setMessage("");
    setDetail(current => current ? { ...current, cards: current.cards.map((row: Row) => row.id === card.id ? { ...row, columnId, position } : row) } : current);
    try {
      const result = await api(`planning/v1/cards/${card.id}/move`, "POST", { expectedRevision: card.revision, expectedBoardRevision: board.revision, columnId, position });
      setDetail(current => current ? { ...current, item: result.board, cards: current.cards.map((row: Row) => row.id === card.id ? result.item : row) } : current);
    } catch (e) { setDetail(saved); setError(`We couldn't confirm your move. The latest saved board is shown. ${errorMessage(e)}`); await refreshBoard("The board could not be refreshed. Refresh before making another change."); }
    finally { setBusy(false); }
  }
  if (!allowed) return <Empty>Planning boards are not available with your current access.</Empty>;
  if (templates) return <StudentBoardTemplates api={api} studentId={studentId} student={student} onClose={() => setTemplates(false)} onCreated={(id) => { setTemplates(false); setBoardId(id); setRevision((n) => n + 1); }} />;
  const learner = ["student", "parent"].includes(business.role);
  return <section className="planning-space" aria-label="Student planning boards"><Notice error={error} message={message} /><div className="student-boards-actions">{boardId && <button disabled={busy} onClick={() => { setBoardId(null); setMessage(""); }}>All boards</button>}<button disabled={loading || busy} onClick={() => setRevision((n) => n + 1)}>Refresh</button>{busy && <span className="planning-save-status" role="status">Saving…</span>}{canCreate && !boardId && <><button onClick={() => setBoardEditor({ sharing: "student" })}>Blank board</button><button className="primary" onClick={() => setTemplates(true)}>Create application plan</button></>}{canManage && board && <><button disabled={busy} onClick={() => setBoardEditor(board)}>Board settings</button>{board.templateKey && <button disabled={busy} onClick={() => setTemplateReview(true)}>Review template version</button>}<button disabled={busy} onClick={() => setColumnEditor({ position: columns.length ? Math.max(...columns.map((row) => row.position)) + 1 : 0 })}>Add column</button></>}</div>
    {loading ? <Empty>Loading planning boards…</Empty> : !boardId ? <>{!boards.length && !error ? <Empty><h3>No planning boards yet.</h3><p>Choose an application path and we’ll organize your next steps. Or start a blank board for any goal.</p></Empty> : <div className="student-board-grid">{boards.map((row) => <article className="student-board-tile" key={row.id}><button onClick={() => setBoardId(row.id)}><h3>{row.name}</h3><p>{row.description}</p><div className="student-board-meta"><span className="tag">{row.sharing === "student" ? "Shared" : "Private"}</span>{row.templateVersion && <span className="tag">Template v{row.templateVersion}</span>}</div><small>Updated {date(row.updatedAt)}</small></button></article>)}</div>}<div className="portal-pagination"><span>{total ? `${offset + 1}–${Math.min(offset + boards.length, total)} of ${total} boards` : ""}</span><button disabled={offset === 0} onClick={() => setOffset((value) => Math.max(0, value - 20))}>Previous boards</button><button disabled={offset + 20 >= total} onClick={() => setOffset((value) => value + 20)}>Next boards</button></div></> : board && <><h2>{board.name}</h2><p className="crm-helper">{board.description}</p><div className="student-board-meta"><span className="tag">{board.sharing === "student" ? (learner ? "Shared with your tutor" : "Shared with student") : "Private"}</span>{board.templateVersion && <span className="tag">Template version {board.templateVersion}</span>}</div><p className="crm-helper">Drag tasks between columns. Open a task for notes, checklists and resources.</p>{!columns.length && <Empty>This board has no columns yet.{canManage ? " Add a column to begin." : " Your tutor can add columns."}</Empty>}<StudentBoardKanban columns={columns} cards={cards} canWrite={canWrite} canManage={canManage} busy={busy} onMove={move} onEdit={setCardEditor} onAdd={(column, position) => setCardEditor({ columnId: column.id, position })} onColumn={setColumnEditor} /></>}
    {boardEditor && <BoardEditor api={api} studentId={studentId} board={boardEditor} onClose={() => setBoardEditor(null)} onSaved={(id) => { setBoardEditor(null); setBoardId(id); setRevision((n) => n + 1); }} />}
    {columnEditor && board && <ColumnEditor api={api} board={board} column={columnEditor} columns={columns} cards={cards} onClose={() => setColumnEditor(null)} onSaved={refreshBoard} />}
    {cardEditor && board && <StudentBoardCard api={api} business={business} studentId={studentId} board={board} columns={columns} card={cardEditor} canWrite={canWrite} onClose={() => setCardEditor(null)} onSaved={refreshBoard} />}
    {templateReview && board && <StudentBoardTemplateReview api={api} board={board} cards={cards} onClose={() => setTemplateReview(false)} onSaved={refreshBoard} />}
  </section>;
}

function BoardEditor({ api, studentId, board, onClose, onSaved }: { api: Api; studentId: string; board: Row; onClose: () => void; onSaved: (id: string | null) => void }) {
  const [name, setName] = useState(board.name ?? ""), [description, setDescription] = useState(board.description ?? ""), [sharing, setSharing] = useState(board.sharing ?? "private"), [busy, setBusy] = useState(false), [error, setError] = useState(""), [deleting, setDeleting] = useState(false), [confirmed, setConfirmed] = useState(false), [requestKey] = useState(() => crypto.randomUUID());
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const data = await api(`planning/v1/boards${board.id ? `/${board.id}` : ""}`, board.id ? "PATCH" : "POST", { name: name.trim(), description, sharing, ...(board.id ? { expectedRevision: board.revision } : { studentId }) }, board.id ? undefined : requestKey); onSaved(data.item.id); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function remove() { if (!confirmed) return; setBusy(true); setError(""); try { await api(`planning/v1/boards/${board.id}`, "DELETE", { expectedRevision: board.revision }); onSaved(null); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title={board.id ? "Board settings" : "Create planning board"} onClose={() => { if (!busy) onClose(); }}><Notice error={error} /><form onSubmit={(e) => void save(e)}><fieldset className="crm-record-fieldset" disabled={busy}><label>Board name<input required maxLength={200} value={name} onChange={(e) => setName(e.target.value)} /></label><label>Description<textarea maxLength={10000} rows={3} value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>Visibility<select value={sharing} onChange={(e) => setSharing(e.target.value)}><option value="private">Creator and business administrators</option><option value="student">Shared with student and authorized guardians</option></select></label><p className="crm-helper">Private boards are visible only to their creator and authorized business administrators. Shared boards appear in the student portal. Contacts and other student records keep their existing access rules.</p></fieldset><div className="form-actions"><button type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving…" : "Save board"}</button></div></form>{board.id && <div className="student-board-danger">{deleting ? <><label className="student-board-checklist-row"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />Permanently delete this board, its columns, tasks and checklists.</label><button disabled={busy || !confirmed} onClick={() => void remove()}>Confirm delete board</button><button disabled={busy} onClick={() => setDeleting(false)}>Cancel deletion</button></> : <button onClick={() => setDeleting(true)}>Delete board</button>}</div>}</Modal>;
}

function ColumnEditor({ api, board, column, columns, cards, onClose, onSaved }: { api: Api; board: Row; column: Row; columns: Row[]; cards: Row[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(column.name ?? ""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [deleting, setDeleting] = useState(false), [confirmed, setConfirmed] = useState(false), [target, setTarget] = useState(""), [requestKey] = useState(() => crypto.randomUUID());
  const ordered = [...columns].sort((a, b) => a.position - b.position || a.id.localeCompare(b.id));
  const originalBefore = ordered[ordered.findIndex(row => row.id === column.id) + 1]?.id ?? "last";
  const [beforeId, setBeforeId] = useState(originalBefore);
  const count = cards.filter((card) => card.columnId === column.id).length;
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); const other = ordered.filter(row => row.id !== column.id), at = beforeId === "last" ? other.length : other.findIndex(row => row.id === beforeId); const position = positionBetween(other[at - 1]?.position, other[at]?.position); try { await api(`planning/v1/boards/${board.id}/columns${column.id ? `/${column.id}` : ""}`, column.id ? "PATCH" : "POST", { name: name.trim(), expectedBoardRevision: board.revision, ...(column.id ? { expectedRevision: column.revision, ...(beforeId !== originalBefore ? { position } : {}) } : { position: column.position }) }, column.id ? undefined : requestKey); await onSaved(); onClose(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function remove() { if (!confirmed || count && !target) return; setBusy(true); setError(""); try { await api(`planning/v1/boards/${board.id}/columns/${column.id}`, "DELETE", { expectedRevision: column.revision, expectedBoardRevision: board.revision, ...(target ? { moveCardsToColumnId: target } : {}) }); await onSaved(); onClose(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title={column.id ? "Column settings" : "Add column"} onClose={() => { if (!busy) onClose(); }}><Notice error={error} /><form onSubmit={(e) => void save(e)}><label>Column name<input disabled={busy} required maxLength={200} value={name} onChange={(e) => setName(e.target.value)} /></label>{column.id && columns.length > 1 && <label>Column order<select disabled={busy} value={beforeId} onChange={event => setBeforeId(event.target.value)}>{ordered.filter(row => row.id !== column.id).map(row => <option key={row.id} value={row.id}>Before {row.name}</option>)}<option value="last">Last column</option></select></label>}<div className="form-actions"><button disabled={busy} type="button" onClick={onClose}>Cancel</button><button disabled={busy} className="primary">Save column</button></div></form>{column.id && <div className="student-board-danger">{deleting ? <>{count > 0 && <label>Move {count} task(s) before deleting<select disabled={busy} value={target} onChange={(e) => setTarget(e.target.value)}><option value="">Choose another column</option>{columns.filter((row) => row.id !== column.id).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>}<label className="student-board-checklist-row"><input disabled={busy} type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />Delete this column{count ? " and move its tasks to the chosen column" : ""}.</label><button disabled={busy || !confirmed || !!count && !target} onClick={() => void remove()}>Confirm delete column</button><button disabled={busy} onClick={() => setDeleting(false)}>Cancel deletion</button></> : <button onClick={() => setDeleting(true)}>Delete column</button>}</div>}</Modal>;
}
