import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, Folder, Plus, Search, SlidersHorizontal } from "lucide-react";
import { canReadFinancial, hasPermission } from "@palladium/contracts";
import { errorMessage, type Api, type Business, type Row } from "../lib/api";
import { Empty, Modal, Notice } from "../components/shared";
import { navigateTutor, readTrackerLocation } from "../lib/tutor-workspace";
import { FiltersDialog, type CRMField, type CRMFilter } from "./crm-controls";
import { StudentPicker } from "./student-picker";
import { StudentInvitations } from "./student-invitations";
import { StudentAvatar, StudentTrackerDetail } from "./student-tracker-detail";
import { ReportingCardSummary, reportingMonth, reportingTimeZone } from "./student-reporting";
import "./student-tracker.css";

export function StudentTracker({ api, business, onOpenLearning, onOpenPlanning, onOpenCRM }: { api: Api; business: Business; onOpenCRM?: (studentId: string) => void; onOpenLearning?: (studentId: string, assignmentId?: string) => void; onOpenPlanning?: (studentId: string) => void }) {
  const canRead = hasPermission(business, "clients.read"), canManage = hasPermission(business, "clients.groups.manage"), canInvite = hasPermission(business, "platform.invites.manage");
  const [view, setView] = useState("groups"), [group, setGroup] = useState<Row | null>(null), [groups, setGroups] = useState<Row[]>([]), [groupTotal, setGroupTotal] = useState(0), [groupOffset, setGroupOffset] = useState(0);
  const [rows, setRows] = useState<Row[]>([]), [total, setTotal] = useState(0), [offset, setOffset] = useState(0), [search, setSearch] = useState(""), [sortBy, setSortBy] = useState("displayName"), [sortDirection, setSortDirection] = useState("asc"), [filters, setFilters] = useState<CRMFilter[]>([]), [fields, setFields] = useState<CRMField[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0), [selected, setSelected] = useState<Set<string>>(new Set());
  const [groupEditor, setGroupEditor] = useState<Row | null>(null), [deleting, setDeleting] = useState<Row | null>(null), [removing, setRemoving] = useState(false), [picker, setPicker] = useState(false), [filtering, setFiltering] = useState(false), [student, setStudent] = useState<Row | null>(null), [inviteStudents, setInviteStudents] = useState<Row[] | null>(null);
  const [navigating, setNavigating] = useState(true), [detailTab, setDetailTab] = useState("summary");
  const [month, setMonth] = useState(() => reportingMonth(business)), [summaries, setSummaries] = useState<Record<string, Row>>({}), [summaryLoading, setSummaryLoading] = useState(false), [summaryError, setSummaryError] = useState(""), [summaryRevision, setSummaryRevision] = useState(0), [reconciling, setReconciling] = useState(false);
  const reportingEnabled = business.entitlements.includes("reporting") && hasPermission(business, "reporting.read"), includeFinancial = business.entitlements.includes("billing") && canReadFinancial(business), zone = reportingTimeZone(business), studentKey = rows.map((row) => row.id).join(",");
  const filterKey = JSON.stringify({ view, groupId: group?.id, search, filters });
  useEffect(() => {
    let cancelled = false, generation = 0;
    async function restore() {
      const location = readTrackerLocation(new URLSearchParams(window.location.search), business.id), request = ++generation;
      setNavigating(true); setStudent(null); setInviteStudents(null); setSelected(new Set()); setOffset(0); setSearch(""); setFilters([]); setGroupOffset(0); setError("");
      try {
        const [folder, record] = await Promise.all([
          location.groupId ? api(`clients/v1/groups/${location.groupId}`) : Promise.resolve(null),
          location.studentId ? api(`clients/v1/clients/${location.studentId}`) : Promise.resolve(null),
        ]);
        if (record && record.item.kind !== "student") throw new Error("This contact is not a student. Open it in the CRM.");
        if (!cancelled && request === generation) { setView(folder ? "groups" : location.view); setGroup(folder?.item ?? null); setStudent(record?.item ?? null); setDetailTab(location.tab); }
      } catch (e) {
        if (!cancelled && request === generation) { setGroup(null); setStudent(null); setView("groups"); setError(errorMessage(e)); navigateTutor(business.id, "tracker", {group:null,student:null,trackerTab:null,trackerView:null}, true); }
      } finally { if (!cancelled && request === generation) setNavigating(false); }
    }
    if (canRead) void restore(); else setNavigating(false);
    window.addEventListener("popstate", restore);
    return () => { cancelled = true; window.removeEventListener("popstate", restore); };
  }, [api, business.id, canRead]);
  function openGroup(item: Row) { setGroup(item); setView("groups"); setStudent(null); setSearch(""); setFilters([]); navigateTutor(business.id, "tracker", {group:item.id,student:null,trackerTab:null,trackerView:null}); }
  function openStudent(row: Row) { setStudent(row); setDetailTab("summary"); navigateTutor(business.id, "tracker", {group:group?.id ?? null,trackerView:view,student:row.id,trackerTab:null}); }
  function closeStudent() { setStudent(null); navigateTutor(business.id, "tracker", {student:null,trackerTab:null}); }
  function selectPage() { setSelected(current => { const next = new Set(current); rows.forEach(row => { if (next.size < 500) next.add(row.id); }); return next; }); }
  useEffect(() => { setOffset(0); setSelected(new Set()); }, [filterKey]);
  useEffect(() => { let cancelled = false; setFields([]); if (canRead) api("clients/v1/fields").then((data) => { if (!cancelled) setFields(data.items ?? []); }).catch((e) => { if (!cancelled) setError(errorMessage(e)); }); return () => { cancelled = true; }; }, [api, canRead]);
  useEffect(() => {
    let cancelled = false; if (!canRead) { setGroups([]); setRows([]); setLoading(false); return; } setLoading(true); setError("");
    const timer = setTimeout(() => {
      const query = new URLSearchParams({ kind: "student", limit: "50", offset: String(offset), sortBy, sortDirection });
      if (group) query.set("groupId", group.id); if (view === "unassigned") query.set("unassigned", "true"); if (search) query.set("search", search); if (filters.length) query.set("filters", JSON.stringify(filters));
      const load = view === "groups" && !group ? api(`clients/v1/groups?limit=50&offset=${groupOffset}`) : api(`clients/v1/clients?${query}`);
      load.then((data) => { if (!cancelled) { if (view === "groups" && !group) { setGroups(data.items ?? []); setGroupTotal(data.total ?? 0); } else { setRows(data.items ?? []); setTotal(data.total ?? 0); } } }).catch((e) => { if (!cancelled) setError(errorMessage(e)); }).finally(() => { if (!cancelled) setLoading(false); });
    }, search ? 250 : 0); return () => { cancelled = true; clearTimeout(timer); };
  }, [api, canRead, filterKey, sortBy, sortDirection, offset, groupOffset, revision]);
  useEffect(() => {
    let cancelled = false; setSummaries({}); setSummaryError("");
    if (!canRead || !reportingEnabled || !rows.length || (view === "groups" && !group) || loading) { setSummaryLoading(false); return; }
    setSummaryLoading(true);
    api("reporting/v1/summaries", "POST", { studentIds: rows.map((row) => row.id), month, timeZone: zone, includeFinancial }).then((data) => { if (!cancelled) setSummaries(Object.fromEntries((data.items ?? []).map((item: Row) => [item.studentId, item]))); }).catch((e) => { if (!cancelled) setSummaryError(errorMessage(e)); }).finally(() => { if (!cancelled) setSummaryLoading(false); });
    return () => { cancelled = true; };
  }, [api, canRead, reportingEnabled, includeFinancial, studentKey, month, zone, loading, view, group?.id, summaryRevision]);
  async function reconcilePage() { if (!reportingEnabled || !hasPermission(business, "reporting.write")) return; setReconciling(true); setSummaryError(""); try { for (let at = 0; at < rows.length; at += 4) await Promise.all(rows.slice(at, at + 4).map((row) => api(`reporting/v1/students/${row.id}/reconcile`, "POST", { month, timeZone: zone, includeFinancial }))); setSummaryRevision((n) => n + 1); } catch (e) { setSummaryError(errorMessage(e)); } finally { setReconciling(false); } }
  function showView(next: string) { navigateTutor(business.id, "tracker", {trackerView:next === "groups" ? null : next,group:null,student:null,trackerTab:null}); setGroup(null); setView(next); setSearch(""); setFilters([]); setError(""); setMessage(""); }
  function changed() { setRevision((n) => n + 1); }
  async function saveGroup(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!canManage) return; const form = new FormData(event.currentTarget); setBusy(true); setError("");
    try { const data = await api(`clients/v1/groups${groupEditor?.id ? `/${groupEditor.id}` : ""}`, groupEditor?.id ? "PATCH" : "POST", { name: String(form.get("name") ?? "").trim(), description: String(form.get("description") ?? "").trim() || null }); if (!groupEditor?.id) openGroup(data.item); else if (group?.id === data.item.id) setGroup(data.item); setGroupEditor(null); changed(); setMessage("Group saved."); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); }
  }
  async function deleteGroup() { if (!deleting || !canManage) return; setBusy(true); setError(""); try { await api(`clients/v1/groups/${deleting.id}`, "DELETE"); if (group?.id === deleting.id) { showView("groups"); } setDeleting(null); changed(); setMessage("Group deleted. Student records are preserved."); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function addStudents(students: Row[], invite: boolean) {
    if (!group || !canManage) return;
    const data = await api(`clients/v1/groups/${group.id}/members`, "POST", { studentIds: students.map((row) => row.id) });
    const ids = new Set<string>(data.studentIds ?? []); setGroup(data.item); setPicker(false); changed(); setMessage(`${ids.size} student${ids.size === 1 ? "" : "s"} added. ${students.length - ids.size ? `${students.length - ids.size} already in the group.` : ""}`);
    if (invite && canInvite && ids.size) setInviteStudents(students.filter((row) => ids.has(row.id)));
  }
  async function removeStudents() { if (!group || !canManage || !selected.size) return; setBusy(true); setError(""); try { const data = await api(`clients/v1/groups/${group.id}/members`, "DELETE", { studentIds: [...selected] }); setGroup(data.item); setRemoving(false); setSelected(new Set()); changed(); setMessage(`${data.studentIds?.length ?? 0} students removed from the group. Student records are preserved.`); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  if (!canRead) return <Empty>You do not have access to the student tracker.</Empty>;
  const folderView = view === "groups" && !group;
  return <div className="student-tracker">
    <div className="section-heading"><div><div className="student-tracker-heading">{group && <button aria-label="Back to groups" onClick={() => showView("groups")}><ArrowLeft size={18} /></button>}<h1>{group?.name ?? "Student tracker"}</h1></div><p className="muted">{group?.description || "Keep students organized by group and open their learning, contacts and session records."}</p></div><div className="heading-actions">{canManage && (group ? <><button onClick={() => setGroupEditor(group)}>Edit group</button><button className="primary" onClick={() => setPicker(true)}><Plus size={16} /> Add students</button></> : <button className="primary" onClick={() => { setError(""); setGroupEditor({}); }}><Plus size={16} /> New group</button>)}</div></div>
    {!group && <div className="student-tracker-views">{["groups", "all", "unassigned"].map((name) => <button key={name} aria-pressed={view === name} onClick={() => showView(name)}>{({ groups: "Groups", all: "All students", unassigned: "Unassigned students" } as Record<string, string>)[name]}</button>)}</div>}
    <Notice error={!groupEditor && !deleting && !removing ? error : ""} message={message} />
    <section className="panel">
      {!folderView && <><div className="toolbar"><label className="search"><Search size={17} /><input aria-label="Search tracker students" placeholder="Name, email or phone" value={search} maxLength={160} onChange={(e) => setSearch(e.target.value)} /></label><select aria-label="Sort tracker students" value={sortBy} onChange={(e) => { setSortBy(e.target.value); setOffset(0); }}><option value="displayName">Name</option><option value="createdAt">Date added</option><option value="status">Stage</option>{fields.map((field) => <option key={field.id} value={`custom:${field.id}`}>{field.label}</option>)}</select><button onClick={() => setSortDirection((current) => current === "asc" ? "desc" : "asc")}>{sortDirection === "asc" ? "Ascending ↑" : "Descending ↓"}</button><button onClick={() => setFiltering(true)}><SlidersHorizontal size={15} /> Filters{filters.length ? ` (${filters.length})` : ""}</button>{(search || filters.length > 0) && <button onClick={() => { setSearch(""); setFilters([]); }}>Clear filters</button>}</div>{group && canManage && !selected.size && <div className="tracker-selection-start"><button disabled={loading || !rows.length} onClick={selectPage}>Select students on this page</button><span className="crm-helper">Select students to manage this group.</span></div>}{group && canManage && selected.size > 0 && <div className="crm-selection"><strong>{selected.size} students selected across pages</strong><button disabled={loading || !rows.length || selected.size >= 500} onClick={() => setSelected((current) => { const next = new Set(current); rows.forEach((row) => { if (next.size < 500) next.add(row.id); }); return next; })}>Select this page</button><button disabled={!selected.size} onClick={() => setSelected(new Set())}>Clear selection</button><button disabled={!selected.size} onClick={() => setRemoving(true)}>Remove from group</button></div>}</>}
      {!folderView && reportingEnabled && <details className="tracker-progress-controls"><summary>Progress for {new Intl.DateTimeFormat(undefined, {month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${month}-01T12:00:00Z`))} · Change month or refresh</summary><div className="toolbar"><label>Summary month<input type="month" min="2000-01" max="2200-12" value={month} disabled={reconciling} onChange={(e) => { if (/^\d{4}-\d{2}$/.test(e.target.value)) setMonth(e.target.value); }} /></label><span className="crm-helper">{zone}</span><button disabled={loading || summaryLoading || reconciling} onClick={() => setSummaryRevision((n) => n + 1)}>Refresh summaries</button>{hasPermission(business, "reporting.write") && <button disabled={loading || !rows.length || reconciling} onClick={() => void reconcilePage()}>{reconciling ? "Updating progress…" : "Update progress from records"}</button>}<Notice error={summaryError} /></div></details>}
      {loading || navigating ? <Empty>Loading {folderView ? "groups" : "students"}…</Empty> : folderView ? !groups.length ? <Empty><Folder size={28} /><h3>No groups yet.</h3><p>Create a group, then add students from your CRM.</p></Empty> : <div className="tracker-group-grid">{groups.map((item) => <article className="tracker-group-card" key={item.id}><button className="tracker-group-open" onClick={() => openGroup(item)}><Folder size={28} /><strong>{item.name}</strong><span>{item.studentCount} student{item.studentCount === 1 ? "" : "s"}</span>{item.description && <span>{item.description}</span>}</button>{canManage && <div className="tracker-actions"><button onClick={() => setGroupEditor(item)}>Rename / edit</button><button onClick={() => { setError(""); setDeleting(item); }}>Delete group</button></div>}</article>)}</div> : !rows.length ? <Empty><h3>No students to show.</h3><p>{view === "unassigned" ? "Every student has a group, or your current filters have no matches." : group ? "Add students from your CRM or clear the current filters." : "Add students in the CRM to see them here."}</p>{group && canManage && <button className="primary" onClick={() => setPicker(true)}>Add students</button>}</Empty> : <div className="tracker-student-grid">{rows.map((row) => <article className="tracker-student-card" key={row.id}><div className="tracker-student-top">{group && canManage && <input type="checkbox" aria-label={`Select ${row.displayName}`} checked={selected.has(row.id)} disabled={!selected.has(row.id) && selected.size >= 500} onChange={(e) => setSelected((current) => { const next = new Set(current); if (e.target.checked && next.size < 500) next.add(row.id); else next.delete(row.id); return next; })} />}<button className="tracker-student-open" onClick={() => openStudent(row)}><StudentAvatar student={row} /><span><strong>{row.displayName}</strong><small>{row.email || "No primary email"}</small></span></button></div><dl className="tracker-properties"><div><dt>Stage</dt><dd><span className={`status ${row.status}`}>{row.status}</span></dd></div>{row.tags?.length > 0 && <div><dt>Tags</dt><dd>{row.tags.join(", ")}</dd></div>}{fields.filter((field) => row.customFields?.[field.id] != null && row.customFields[field.id] !== "").slice(0, 3).map((field) => <div key={field.id}><dt>{field.label}</dt><dd>{field.type === "boolean" ? row.customFields[field.id] ? "Yes" : "No" : String(row.customFields[field.id])}</dd></div>)}</dl>{reportingEnabled && <ReportingCardSummary summary={summaries[row.id]} loading={summaryLoading} error={summaryError} />}</article>)}</div>}
      <div className="pagination"><span>{folderView ? `${groupTotal} group${groupTotal === 1 ? "" : "s"}` : total ? `${offset + 1}–${Math.min(offset + rows.length, total)} of ${total} students` : "0 matching students"}</span>{(folderView ? groupTotal : total) > 50 && <button disabled={loading || (folderView ? groupOffset === 0 : offset === 0)} onClick={() => folderView ? setGroupOffset((n) => Math.max(0, n - 50)) : setOffset((n) => Math.max(0, n - 50))}>Previous</button>}{(folderView ? groupTotal : total) > 50 && <button disabled={loading || (folderView ? groupOffset + 50 >= groupTotal : offset + 50 >= total)} onClick={() => folderView ? setGroupOffset((n) => n + 50) : setOffset((n) => n + 50)}>Next</button>}</div>
    </section>
    {groupEditor && canManage && <Modal title={groupEditor.id ? "Edit group" : "Create group"} onClose={() => { if (!busy) { setGroupEditor(null); setError(""); } }}><Notice error={error} /><form onSubmit={saveGroup}><label>Group name<input name="name" required maxLength={160} defaultValue={groupEditor.name ?? ""} disabled={busy} /></label><label>Description<textarea name="description" maxLength={2000} rows={3} defaultValue={groupEditor.description ?? ""} disabled={busy} /></label><div className="form-actions"><button type="button" disabled={busy} onClick={() => { setGroupEditor(null); setError(""); }}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving…" : "Save group"}</button></div></form></Modal>}
    {deleting && canManage && <Modal title={`Delete ${deleting.name}?`} onClose={() => { if (!busy) { setDeleting(null); setError(""); } }}><Notice error={error} /><p>Delete this group and its memberships? Student records, homework, invoices and portal access will be preserved.</p><div className="form-actions"><button disabled={busy} onClick={() => { setDeleting(null); setError(""); }}>Cancel</button><button disabled={busy} onClick={() => void deleteGroup()}>{busy ? "Deleting…" : "Confirm group deletion"}</button></div></Modal>}
    {removing && group && canManage && <Modal title="Remove students from this group?" onClose={() => { if (!busy) setRemoving(false); }}><Notice error={error} /><p>Remove {selected.size} selected student{selected.size === 1 ? "" : "s"} from {group.name}? Their records and other group memberships will be preserved.</p><div className="form-actions"><button disabled={busy} onClick={() => setRemoving(false)}>Cancel</button><button disabled={busy} onClick={() => void removeStudents()}>{busy ? "Removing…" : "Confirm removal"}</button></div></Modal>}
    {picker && group && canManage && <StudentPicker api={api} groupName={group.name} fields={fields} canInvite={canInvite} onClose={() => setPicker(false)} onAdd={addStudents} />}
    {filtering && <FiltersDialog fields={fields} filters={filters} onApply={setFilters} onClose={() => setFiltering(false)} />}
    {student && !inviteStudents && <StudentTrackerDetail key={student.id} initialTab={detailTab} onTabChange={(tab) => { setDetailTab(tab); navigateTutor(business.id, "tracker", {trackerTab:tab}, true); }} onOpenCRM={onOpenCRM} api={api} business={business} student={student} fields={fields} month={month} onMonthChange={setMonth} onClose={closeStudent} onChanged={changed} onOpenLearning={onOpenLearning} onOpenPlanning={onOpenPlanning ? (id) => { setStudent(null); onOpenPlanning(id); } : undefined} onInvite={(row) => setInviteStudents([row])} />}
    {inviteStudents && <StudentInvitations api={api} business={business} students={inviteStudents} onClose={() => setInviteStudents(null)} />}
  </div>;
}
