import { useEffect, useState } from "react";
import { errorMessage, type Api, type Row } from "../lib/api";
import { Empty, Modal, Notice } from "../components/shared";
import { DeadlineLabel } from "./student-board-card";

export function StudentBoardTemplateReview({ api, board, cards, onClose, onSaved }: { api: Api; board: Row; cards: Row[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [review, setReview] = useState<Row | null>(null), [selected, setSelected] = useState<Set<string>>(new Set()), [confirmed, setConfirmed] = useState(false), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { let cancelled = false; async function load() { const template = await api(`planning/v1/templates/${board.templateKey}`), version = template.item.version; const data = await api(`planning/v1/boards/${board.id}/template-review?version=${version}`); if (!cancelled) setReview(data); } load().catch((e) => { if (!cancelled) setError(errorMessage(e)); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [api, board.id, board.templateKey]);
  async function apply() { if (!review || !confirmed) return; setBusy(true); setError(""); try { await api(`planning/v1/boards/${board.id}/template-apply`, "POST", { version: review.templateVersion, expectedRevision: review.board.revision, cardIds: [...selected] }); await onSaved(); onClose(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title="Review template version" onClose={() => { if (!busy) onClose(); }}><Notice error={error} />{loading ? <Empty>Checking the published template version…</Empty> : review && <><p className="crm-helper">Board version {board.templateVersion} · Published version {review.templateVersion}. Changes are applied only after you select deadlines and confirm. Tasks, checklists and references remain intact; dates edited by users are preserved.</p>{review.templateVersion === board.templateVersion ? <Empty>This board already uses the latest published version.</Empty> : <><div className="student-board-checklist">{review.suggestions.map((suggestion: Row) => <div className="student-template-scope" key={suggestion.cardId}><label className="student-board-checklist-row"><input type="checkbox" disabled={busy || suggestion.preserveUserEdit} checked={selected.has(suggestion.cardId)} onChange={(e) => setSelected((current) => { const next = new Set(current); if (e.target.checked) next.add(suggestion.cardId); else next.delete(suggestion.cardId); return next; })} />{cards.find((card) => card.id === suggestion.cardId)?.title ?? "Template task"}</label>{suggestion.preserveUserEdit && <p className="crm-helper">User edited this deadline. Its date will be preserved.</p>}<p>Current deadline</p>{suggestion.currentDeadline ? <DeadlineLabel deadline={suggestion.currentDeadline} /> : <p className="crm-helper">No deadline</p>}<p>Published deadline</p>{suggestion.proposedDeadline ? <DeadlineLabel deadline={suggestion.proposedDeadline} /> : <p className="crm-helper">No deadline</p>}</div>)}</div>{review.addedCards?.length > 0 && <div className="student-board-banner">The new template includes {review.addedCards.length} additional task(s): {review.addedCards.map((card: Row) => card.title).join(", ")}. They are not added automatically; add relevant tasks yourself after review.</div>}<label className="student-board-checklist-row"><input disabled={busy} type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />I checked the source dates and applicability. Record this version and apply the {selected.size} selected deadline change(s).</label><button className="primary" disabled={busy || !confirmed} onClick={() => void apply()}>{busy ? "Applying selected dates…" : "Confirm selected changes"}</button></>}</>}<div className="form-actions"><button disabled={busy} onClick={onClose}>Close</button></div></Modal>;
}
