'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { featureRegistry } from '@palladium/contracts';
import { ArrowRight, BookOpen, CalendarDays, Check, ChevronDown, CircleDollarSign, ClipboardList, GraduationCap, LayoutDashboard, LogOut, Plus, RefreshCw, Settings2, Users, Wallet, Bell } from 'lucide-react';

type Row = Record<string, any>;
type Business = {id:string;name:string;role:string;entitlements:string[];settings?:Row};
const gateway=process.env.NEXT_PUBLIC_GATEWAY_URL ?? 'http://localhost:8080';
const icons:Record<string,any>={clients:Users,scheduling:CalendarDays,learning:BookOpen,billing:ClipboardList,payments:Wallet,notifications:Bell};
const endpoints:Record<string,string>={clients:'clients',scheduling:'sessions',learning:'assignments',billing:'invoices',payments:'checkouts',notifications:'notifications'};
const descriptions:Record<string,string>={clients:'The people at the heart of your practice.',scheduling:'Make room for meaningful one-to-one learning.',learning:'Keep the next step clear for every student.',billing:'A clear view of what is due and what is paid.',payments:'Your business. Your choice of payment methods.',notifications:'The latest activity across your workspace.'};
const money=(amount:number,currency='USD')=>new Intl.NumberFormat('en',{style:'currency',currency}).format(amount/(10**(new Intl.NumberFormat('en',{style:'currency',currency}).resolvedOptions().maximumFractionDigits ?? 2)));
const date=(value:string)=>new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});

export default function Home(){
 const [session,setSession]=useState<Row|null>(null),[businesses,setBusinesses]=useState<Business[]>([]),[business,setBusiness]=useState<Business|null>(null);
 const [view,setView]=useState('overview'),[rows,setRows]=useState<Row[]>([]),[clients,setClients]=useState<Row[]>([]),[invoices,setInvoices]=useState<Row[]>([]),[connections,setConnections]=useState<Row[]>([]),[counts,setCounts]=useState<Record<string,number>>({});
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[register,setRegister]=useState(false),[showForm,setShowForm]=useState(false);
 async function api(path:string,method='GET',body?:unknown,tenant=business?.id):Promise<any>{
  const response=await fetch(`${gateway}/api/${path}`,{method,credentials:'include',headers:{'content-type':'application/json',...(tenant?{'X-Business-Id':tenant}:{}),...(['POST','PATCH'].includes(method)?{'Idempotency-Key':crypto.randomUUID()}: {})},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const data=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(data.error?.message ?? data.message ?? `Request failed (${response.status})`);
  return data;
 }
 async function loadBusiness(){const response=await api('platform/v1/businesses');setBusinesses(response.items);setBusiness(current=>response.items.find((b:Business)=>b.id===current?.id) ?? response.items[0] ?? null);}
 useEffect(()=>{(async()=>{try{const result=await api('platform/v1/session');if(result.item){setSession(result.item);await loadBusiness();}}catch{}finally{setLoading(false);}})();},[]);
 async function refresh(){
  if(!business)return;setError('');setLoading(true);
  try{
   if(view==='overview'){
    const results=await Promise.allSettled(featureRegistry.filter(f=>business.entitlements.includes(f.id)).map(async f=>[f.id,(await api(`${f.id}/v1/${endpoints[f.id]}`)).items.length] as const));
    setCounts(Object.fromEntries(results.filter(r=>r.status==='fulfilled').map(r=>(r as PromiseFulfilledResult<readonly [string,number]>).value)));
   }else if(view!=='settings')setRows((await api(`${view}/v1/${endpoints[view]}`)).items);
   if(['scheduling','learning','billing'].includes(view) && business.entitlements.includes('clients'))setClients((await api('clients/v1/clients')).items);
   if(view==='payments'){
    setConnections((await api('payments/v1/connections')).items);
    if(business.entitlements.includes('billing'))setInvoices((await api('billing/v1/invoices')).items);
   }
  }catch(e){setError((e as Error).message);}finally{setLoading(false);}
 }
 useEffect(()=>{setRows([]);setShowForm(false);setNotice('');void refresh();},[business?.id,view]);
 async function act(work:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await work();setNotice(message);setShowForm(false);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await api(`platform/auth/${register?'sign-up':'sign-in'}/email`,'POST',{email:f.get('email'),password:f.get('password'),...(register?{name:f.get('name')}:{})});const result=await api('platform/v1/session');setSession(result.item);await loadBusiness();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const userName=session?.user?.name ?? 'Your';
 const enabled=featureRegistry.filter(f=>business?.entitlements.includes(f.entitlement));
 const title=view==='overview'?'A little clarity for your day.':view==='settings'?'Make yourself at home.':featureRegistry.find(f=>f.id===view)?.label;
 function input(label:string,name:string,type='text',required=true,placeholder=''){return <label>{label}<input name={name} type={type} required={required} placeholder={placeholder}/></label>;}
 function studentSelect(){return <label>Student<select name="clientId" required><option value="">Choose a student</option>{clients.filter(c=>c.kind==='student').map(c=><option key={c.id} value={c.id}>{c.displayName}</option>)}</select></label>;}
 async function createRecord(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const v=(k:string)=>String(f.get(k)??'');
  await act(async()=>{
   if(view==='clients')await api('clients/v1/clients','POST',{displayName:v('displayName'),kind:v('kind'),...(v('email')?{email:v('email')}:{})});
   if(view==='scheduling'){const startsAt=new Date(v('startsAt'));await api('scheduling/v1/sessions','POST',{clientId:v('clientId'),title:v('title'),startsAt:startsAt.toISOString(),endsAt:new Date(startsAt.getTime()+Number(v('duration'))*60000).toISOString()});}
   if(view==='learning')await api('learning/v1/assignments','POST',{clientId:v('clientId'),title:v('title'),description:v('description'),...(v('dueAt')?{dueAt:new Date(v('dueAt')).toISOString()}:{})});
   if(view==='billing'){const [whole,fraction='']=v('price').split('.');const unitPriceMinor=Number(whole)*100+Number(fraction.padEnd(2,'0').slice(0,2));await api('billing/v1/invoices','POST',{payerName:v('payerName'),currency:v('currency'),items:[{description:v('description'),quantity:1,unitPriceMinor}]});}
   if(view==='payments')await api('payments/v1/checkouts','POST',{invoiceId:v('invoiceId'),connectionId:v('connectionId')});
  },'Saved to your workspace.');
 }
 if(!session)return <main className="auth"><div className="auth-story"><div className="wordmark"><GraduationCap/> tuts</div><div><span className="eyebrow light">ROOM TO TEACH</span><h1>Your practice.<br/>All together.</h1><p>Space for your students, your schedule,<br/>and the way you work.</p></div><div className="auth-foot"><span className="little-star">✳</span> Built around independent educators.</div></div><div className="auth-panel"><div className="auth-card"><span className="eyebrow">YOUR WORKSPACE</span><h2>{register?'Start something good.':'Welcome back.'}</h2><p className="muted">{register?'Create your account, then set up your tutoring business.':'Sign in to pick up where you left off.'}</p>{error&&<div className="alert error">{error}</div>}<form onSubmit={authenticate}>{register&&input('Your name','name')}{input('Email address','email','email')}{input('Password','password','password')}<button className="primary full" disabled={busy||loading}>{busy?'Please wait…':register?'Create account':'Sign in'}<ArrowRight size={17}/></button></form><button className="link" onClick={()=>{setRegister(!register);setError('');}}>{register?'Already have an account? Sign in':'New here? Create an account'}</button><div className="small-note">Local development preview · Payments are simulated.</div></div></div></main>;
 if(!business)return <main className="onboarding"><div className="auth-card"><GraduationCap size={34}/><h1>A home for your business.</h1><p className="muted">Give your workspace a name. You can make it your own as you go.</p>{error&&<div className="alert error">{error}</div>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await api('platform/v1/businesses','POST',{name:f.get('name'),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});await loadBusiness();},'Workspace created.');}}>{input('Business name','name','text',true,'Your tutoring business')}<button className="primary full" disabled={busy}>Create workspace<ArrowRight size={17}/></button></form></div></main>;
 return <div className="shell" style={{'--accent':business.settings?.branding?.primaryColor ?? '#315d4d'} as React.CSSProperties}>
  <aside><div className="wordmark"><GraduationCap/> tuts</div><div className="business-picker"><span className="avatar">{business.name.slice(0,1)}</span><select aria-label="Business workspace" value={business.id} onChange={e=>{setBusiness(businesses.find(b=>b.id===e.target.value)!);setView('overview');}}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><ChevronDown size={14}/></div><span className="nav-caption">WORKSPACE</span><nav><button className={view==='overview'?'active':''} onClick={()=>setView('overview')}><LayoutDashboard size={18}/>Overview</button>{enabled.map(f=>{const Icon=icons[f.id];return <button key={f.id} className={view===f.id?'active':''} onClick={()=>setView(f.id)}><Icon size={18}/>{f.label}</button>;})}</nav><div className="sidebar-bottom"><button onClick={()=>setView('settings')}><Settings2 size={18}/>Workspace settings</button><div className="profile"><span className="avatar pale">{userName[0]}</span><div><strong>{userName}</strong><small>{business.role}</small></div><button title="Sign out" aria-label="Sign out" onClick={()=>void act(async()=>{await api('platform/auth/sign-out','POST',{});setSession(null);setBusiness(null);},'')}><LogOut size={17}/></button></div></div></aside>
  <section className="workspace"><header><div><span className="muted">Workspace</span><span className="slash">/</span>{view==='overview'?'Overview':view==='settings'?'Settings':featureRegistry.find(f=>f.id===view)?.label}</div><span className="preview"><span/>Development preview</span></header><main className="content"><div className="page-heading"><div><span className="eyebrow">{view==='overview'?`WELCOME, ${userName.split(' ')[0].toUpperCase()}`:business.name.toUpperCase()}</span><h1>{title}</h1><p className="muted">{view==='overview'?'More time for the work that matters.':view==='settings'?'Choose the details that make this workspace yours.':descriptions[view]}</p></div><div className="heading-actions"><button className="icon-button" title="Refresh" onClick={()=>void refresh()}><RefreshCw size={17}/></button>{!['overview','settings','notifications'].includes(view)&&<button className="primary" onClick={()=>setShowForm(!showForm)}><Plus size={16}/>{view==='clients'?'Add client':view==='scheduling'?'Book session':view==='learning'?'Add assignment':view==='billing'?'New invoice':'New payment'}</button>}</div></div>
  {error&&<div role="alert" className="alert error">{error}</div>}{notice&&<div role="status" className="alert success"><Check size={16}/>{notice}</div>}
  {view==='overview'?<><div className="stat-grid">{enabled.slice(0,4).map(f=>{const Icon=icons[f.id];return <button className="stat-card" key={f.id} onClick={()=>setView(f.id)}><div><span>{f.label}</span><Icon size={20}/></div><strong>{counts[f.id]??'—'}</strong><small>Open {f.label.toLowerCase()} <ArrowRight size={13}/></small></button>;})}</div><div className="overview-grid"><section className="welcome-card"><span className="eyebrow">A PRACTICE THAT FITS YOU</span><h2>Good teaching starts<br/>with a little breathing room.</h2><p>Start with a student, book a session, and keep their next step close at hand.</p><button onClick={()=>setView(business.entitlements.includes('clients')?'clients':'settings')}>Set things in motion <ArrowRight size={17}/></button><div className="decor-circle">✳</div></section><section className="panel"><div className="panel-title"><h3>Your workspace</h3><span className="tag">{enabled.length} features</span></div>{enabled.map(f=>{const Icon=icons[f.id];return <button className="feature-row" key={f.id} onClick={()=>setView(f.id)}><span className="feature-icon"><Icon size={18}/></span><span>{f.label}<small>Available in this workspace</small></span><ArrowRight size={16}/></button>;})}</section></div></>:view==='settings'?<section className="panel settings"><h3>Business identity</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await api(`platform/v1/businesses/${business.id}/settings`,'PATCH',{branding:{displayName:f.get('displayName'),primaryColor:f.get('color')},timezone:f.get('timezone')});await loadBusiness();},'Workspace updated.');}}><label>Display name<input name="displayName" defaultValue={business.settings?.branding?.displayName??business.name} required/></label><label>Brand color<input name="color" type="color" defaultValue={business.settings?.branding?.primaryColor??'#315d4d'}/></label><label>Timezone<input name="timezone" defaultValue={business.settings?.timezone??'UTC'} required/></label><button className="primary" disabled={busy}>Save changes</button></form><p className="small-note">Feature access is managed by the platform. Your settings only affect this business.</p></section>:<>
  {view==='payments'&&<div className="payment-banner"><div><Wallet size={23}/><div><strong>Payment connections</strong><p>Stripe, PayPal, and bank integrations are planned. This preview supports a clearly labeled local sandbox only.</p></div></div><button disabled={busy||connections.some(c=>c.provider==='sandbox')} onClick={()=>void act(()=>api('payments/v1/connections','POST',{provider:'sandbox',displayName:'Local sandbox'}),'Sandbox connection enabled.')}>{connections.some(c=>c.provider==='sandbox')?'Sandbox connected':'Enable sandbox'}</button></div>}
  {showForm&&<section className="panel create-panel"><h3>{view==='clients'?'Add someone new':view==='scheduling'?'Plan a session':view==='learning'?'Set the next step':view==='billing'?'Create an invoice':'Create a sandbox payment'}</h3><form onSubmit={createRecord}><div className="form-grid">{view==='clients'&&<>{input('Full name','displayName')}<label>Client type<select name="kind"><option value="student">Student</option><option value="payer">Parent / payer</option></select></label>{input('Email address','email','email',false)}</>}{view==='scheduling'&&<>{studentSelect()}{input('Session title','title')}{input('Starts at','startsAt','datetime-local')}<label>Duration<select name="duration"><option value="60">60 minutes</option><option value="30">30 minutes</option><option value="90">90 minutes</option></select></label></>}{view==='learning'&&<>{studentSelect()}{input('Assignment title','title')}{input('Instructions','description','text',false)}{input('Due at','dueAt','datetime-local',false)}</>}{view==='billing'&&<>{input('Bill to','payerName')}{input('Description','description')}<label>Currency<select name="currency"><option>USD</option><option>EUR</option><option>GBP</option><option>MAD</option></select></label><label>Amount<input name="price" type="number" step="0.01" min="0.01" required/></label></>}{view==='payments'&&<><label>Issued invoice<select name="invoiceId" required><option value="">Choose an invoice</option>{invoices.filter(i=>i.status==='issued').map(i=><option key={i.id} value={i.id}>{i.payerName} · {money(i.totalMinor,i.currency)}</option>)}</select></label><label>Payment connection<select name="connectionId" required><option value="">Choose a connection</option>{connections.map(c=><option key={c.id} value={c.id}>{c.displayName} (simulated)</option>)}</select></label></>}</div><div className="form-actions"><button type="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></div></form></section>}
  <section className="panel data-panel"><div className="panel-title"><h3>{view==='clients'?'Your people':view==='scheduling'?'Session schedule':view==='learning'?'Student assignments':view==='billing'?'All invoices':view==='payments'?'Payment activity':'Workspace activity'}</h3><span className="tag">{rows.length} {rows.length===1?'record':'records'}</span></div>{loading?<div className="empty">Loading your workspace…</div>:rows.length===0?<div className="empty"><div className="empty-icon">{view==='clients'?<Users/>:view==='scheduling'?<CalendarDays/>:view==='payments'?<CircleDollarSign/>:<BookOpen/>}</div><h3>A fresh start.</h3><p>{view==='notifications'?'Activity will appear as you work.':`Add your first ${view==='clients'?'client':view==='scheduling'?'session':view==='learning'?'assignment':view==='billing'?'invoice':'payment'} to get started.`}</p></div>:<div className="record-list">{rows.map(row=><div className="record" key={row.id}><div className="record-avatar">{(row.displayName??row.title??row.payerName??'P')[0]}</div><div className="record-main"><strong>{row.displayName??row.title??row.payerName??`Payment ${row.id.slice(0,8)}`}</strong><small>{view==='clients'?row.email??'No email added':view==='scheduling'?date(row.startsAt):view==='learning'?row.description??(row.dueAt?`Due ${date(row.dueAt)}`:'No due date'):view==='billing'?row.items?.map((i:Row)=>i.description).join(', '):view==='payments'?'Local sandbox · No real money moved':row.message??'Activity recorded'}</small></div>{['billing','payments'].includes(view)&&<strong className="amount">{money(row.totalMinor??row.amountMinor,row.currency)}</strong>}<span className={`status ${row.status??row.kind}`}>{row.status??row.kind??'queued'}</span><div className="record-actions">{view==='scheduling'&&row.status==='scheduled'&&<><button disabled={busy} onClick={()=>void act(()=>api(`scheduling/v1/sessions/${row.id}/complete`,'POST',{}),'Session completed.')}>Complete</button><button disabled={busy} onClick={()=>void act(()=>api(`scheduling/v1/sessions/${row.id}/cancel`,'POST',{}),'Session cancelled.')}>Cancel</button></>}{view==='billing'&&row.status==='draft'&&<button disabled={busy} onClick={()=>void act(()=>api(`billing/v1/invoices/${row.id}/issue`,'POST',{}),'Invoice issued.')}>Issue invoice</button>}{view==='payments'&&row.status==='pending'&&row.simulated&&<button disabled={busy} onClick={()=>void act(()=>api(`payments/v1/checkouts/${row.id}/sandbox-confirm`,'POST',{}),'Simulated payment confirmed. Refresh invoices shortly to see settlement.')}>Simulate payment</button>}</div></div>)}</div>}</section></>}
  <footer>Tuts <span>·</span> A workspace for better teaching.</footer></main></section>
 </div>;
}
