ALTER TABLE invoices ADD COLUMN service_month date;
ALTER TABLE invoices ADD COLUMN due_at timestamptz;
ALTER TABLE invoices ADD COLUMN class_ids text[] NOT NULL DEFAULT '{}';
CREATE UNIQUE INDEX invoices_student_month_unique ON invoices(business_id,client_id,service_month) WHERE service_month IS NOT NULL;
ALTER TABLE payment_allocations ADD COLUMN simulated boolean NOT NULL DEFAULT false;
UPDATE payment_allocations SET simulated=true WHERE provider='sandbox';
CREATE TABLE billing_settings (business_id uuid PRIMARY KEY,time_zone text NOT NULL DEFAULT 'UTC',auto_draft boolean NOT NULL DEFAULT false,last_draft_month date,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE student_rates (business_id uuid NOT NULL,id uuid NOT NULL,client_id uuid NOT NULL,payer_name text NOT NULL,currency text NOT NULL CHECK(currency ~ '^[A-Z]{3}$'),unit_price_minor bigint NOT NULL CHECK(unit_price_minor>0 AND unit_price_minor<=9007199254740991),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(business_id,id),UNIQUE(business_id,client_id));
CREATE TABLE billing_classes (business_id uuid NOT NULL,class_id uuid NOT NULL,source text NOT NULL CHECK(source IN ('internal','external')),client_id uuid,title text NOT NULL DEFAULT 'Class',attendee_email text,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,status text NOT NULL CHECK(status IN ('scheduled','completed','cancelled')),revision bigint NOT NULL CHECK(revision>0),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(business_id,source,class_id),CHECK(ends_at>starts_at));
CREATE INDEX billing_classes_month ON billing_classes(business_id,starts_at);
CREATE TABLE billed_classes (business_id uuid NOT NULL,source text NOT NULL,class_id uuid NOT NULL,invoice_id uuid NOT NULL,revision bigint NOT NULL,PRIMARY KEY(business_id,source,class_id),FOREIGN KEY(business_id,invoice_id) REFERENCES invoices(business_id,id));
CREATE TABLE monthly_reconciliations (business_id uuid NOT NULL,month date NOT NULL,time_zone text NOT NULL,reconciled_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(business_id,month,time_zone));
ALTER TABLE billing_settings ENABLE ROW LEVEL SECURITY; ALTER TABLE billing_settings FORCE ROW LEVEL SECURITY;
CREATE POLICY billing_settings_tenant ON billing_settings USING (business_id = nullif(current_setting('app.business_id',true),'')::uuid) WITH CHECK (business_id = nullif(current_setting('app.business_id',true),'')::uuid);
ALTER TABLE student_rates ENABLE ROW LEVEL SECURITY; ALTER TABLE student_rates FORCE ROW LEVEL SECURITY;
CREATE POLICY student_rates_tenant ON student_rates USING (business_id = nullif(current_setting('app.business_id',true),'')::uuid) WITH CHECK (business_id = nullif(current_setting('app.business_id',true),'')::uuid);
ALTER TABLE billing_classes ENABLE ROW LEVEL SECURITY; ALTER TABLE billing_classes FORCE ROW LEVEL SECURITY;
CREATE POLICY billing_classes_tenant ON billing_classes USING (business_id = nullif(current_setting('app.business_id',true),'')::uuid) WITH CHECK (business_id = nullif(current_setting('app.business_id',true),'')::uuid);
ALTER TABLE billed_classes ENABLE ROW LEVEL SECURITY; ALTER TABLE billed_classes FORCE ROW LEVEL SECURITY;
CREATE POLICY billed_classes_tenant ON billed_classes USING (business_id = nullif(current_setting('app.business_id',true),'')::uuid) WITH CHECK (business_id = nullif(current_setting('app.business_id',true),'')::uuid);
ALTER TABLE monthly_reconciliations ENABLE ROW LEVEL SECURITY; ALTER TABLE monthly_reconciliations FORCE ROW LEVEL SECURITY;
CREATE POLICY monthly_reconciliations_tenant ON monthly_reconciliations USING (business_id = nullif(current_setting('app.business_id',true),'')::uuid) WITH CHECK (business_id = nullif(current_setting('app.business_id',true),'')::uuid);
